services:
  - type: web
    name: pastebin-lite-backend
    runtime: node
    repo: https://github.com/priyankakommani/pastebin-lite-v2
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_VERSION
        value: 20.9.0
      - key: TEST_MODE
        value: 0
      - key: DATABASE_URL
        sync: false # User will provide this in the dashboard
